### PR TITLE
Update SMK, npm dependencies with vulnerabilities

### PR DESCRIPTION
**Pull request by michaelpnelson**
link to demo deployment of your smk based app is 
 https://smk-firewood-rt-b16795-dev.apps.silver.devops.gov.bc.ca

Verify that it looks good, if so merge the pull request which will trigger a prod deployment, otherwise close the pull request without merging

 mentions / notifications: @GuyTheFlower, @NicoledeGreef, @franTarkenton

### CODE REVIEW

**Comment by dgboss** [comment]
The Vanity URL for the dev deploy is https://smk-firewood-api-gov-bc-ca.test.api.gov.bc.ca
 

If this is a dev deploy,  verify that it looks good, then merge the pull request to trigger prod deployment.

 If this is a prod deployment, view your prod deploy at the url above :)

 mentions / notifications: @GuyTheFlower, @NicoledeGreef, @franTarkenton

**Comment by michaelpnelson** [comment]
I've added a commit to this PR that updates the SMK dependency to 1.1.2, so that Firewood gets the Geomark fix. 

I'll close this PR and then reopen it to trigger a dev deploy. After manual testing and acceptance, I'll merge these changes.

**Comment by michaelpnelson** [comment]
The deploy to dev triggered by reopening this PR failed while executing an 'oc login' command. The IP and port look correct; perhaps the token is expired. I'll close and reopen this PR to see if the problem persists in case it was a one-off.

**Comment by dgboss** [comment]
The Vanity URL for the dev deploy is https://smk-firewood-api-gov-bc-ca.test.api.gov.bc.ca
 

If this is a dev deploy,  verify that it looks good, then merge the pull request to trigger prod deployment.

 If this is a prod deployment, view your prod deploy at the url above :)

 mentions / notifications: @GuyTheFlower, @NicoledeGreef, @franTarkenton

**Review by dgboss — APPROVED** [review]

**Comment by michaelpnelson** [comment]
I confirmed the Geomark fix in QA. I'll merge this.

**Comment by dgboss** [comment]
link to demo deployment of your smk based app is 
 https://smk-firewood-rt-b16795-prod.apps.silver.devops.gov.bc.ca

Verify that it looks good, if so merge the pull request which will trigger a prod deployment, otherwise close the pull request without merging

 mentions / notifications: @GuyTheFlower, @NicoledeGreef, @franTarkenton

**Comment by dgboss** [comment]
The Vanity URL for the prod deploy is https://smk-firewood.api.gov.bc.ca
 

If this is a dev deploy,  verify that it looks good, then merge the pull request to trigger prod deployment.

 If this is a prod deployment, view your prod deploy at the url above :)

 mentions / notifications: @GuyTheFlower, @NicoledeGreef, @franTarkenton

**Pull request merged**
